name=rp2040-uni
version=1.0.0
author=OpenDev
maintainer=OpenDev <opendevmobile@proton.me>
sentence=Universal Libary RP2350 
paragraph=This library can be used with any RP2350 board, such as RPI Pico 2.
category=Sensor
url=https://github.com/gbr1/rp2040-encoder-library
architectures=rp2350
includes=rp2350_uni.h
