name=RP2350_UNI
version=1.0.0
author=OpenSourceDevelop
maintainer=OpenSourceDevelop <opendevmobile@proton.me>
sentence=A high-performance PIO, WS2812, Encoder, and System helper for RP2040/RP2350.
paragraph=Provides Hardware PIO Quadrature Encoder decoding with acceleration, WS2812 LED control, ADC, Watchdog, and debounced buttons.
category=Device Control
url=https://github.com/OpenSourceDevelop/rp2350_uni
architectures=rp2040,rp2350
includes=rp2350_uni.h